// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBusinessMember = `-- name: AddBusinessMember :one
INSERT INTO business_members (
    user_id,
    business_id,
    role
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, business_id, role, current_balance, created_at
`

type AddBusinessMemberParams struct {
	UserID     pgtype.UUID  `json:"user_id"`
	BusinessID pgtype.UUID  `json:"business_id"`
	Role       BusinessRole `json:"role"`
}

// Adds a user to a business with a specific role, returning the new membership record.
func (q *Queries) AddBusinessMember(ctx context.Context, arg AddBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, addBusinessMember, arg.UserID, arg.BusinessID, arg.Role)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Role,
		&i.CurrentBalance,
		&i.CreatedAt,
	)
	return i, err
}

const checkAdmin = `-- name: CheckAdmin :one
SELECT 1
FROM business_members
WHERE user_id = $1 AND business_id = $2 AND role in ('admin', 'creator')
`

type CheckAdminParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// returns 1 if a user is admin or creator of a given business_id
func (q *Queries) CheckAdmin(ctx context.Context, arg CheckAdminParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkAdmin, arg.UserID, arg.BusinessID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createBusinessAndAddOwner = `-- name: CreateBusinessAndAddOwner :one
SELECT id, name, owner_id, created_at, updated_at, current_plan_id, subscriptions_status, subscription_end_period, is_trial_used, current_subscription_id, is_offer_used FROM create_business_and_add_owner(
    p_owner_id := $1,
    p_name := $2
)
`

type CreateBusinessAndAddOwnerParams struct {
	POwnerID pgtype.UUID `json:"p_owner_id"`
	PName    string      `json:"p_name"`
}

func (q *Queries) CreateBusinessAndAddOwner(ctx context.Context, arg CreateBusinessAndAddOwnerParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusinessAndAddOwner, arg.POwnerID, arg.PName)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentPlanID,
		&i.SubscriptionsStatus,
		&i.SubscriptionEndPeriod,
		&i.IsTrialUsed,
		&i.CurrentSubscriptionID,
		&i.IsOfferUsed,
	)
	return i, err
}

const deleteBusiness = `-- name: DeleteBusiness :exec
DELETE FROM businesses WHERE id = $1
`

// used to delete a business
func (q *Queries) DeleteBusiness(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBusiness, id)
	return err
}

const deleteBusinessMember = `-- name: DeleteBusinessMember :exec
DELETE FROM business_members WHERE user_id = $1 AND business_id = $2
`

type DeleteBusinessMemberParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// used to remove business member
func (q *Queries) DeleteBusinessMember(ctx context.Context, arg DeleteBusinessMemberParams) error {
	_, err := q.db.Exec(ctx, deleteBusinessMember, arg.UserID, arg.BusinessID)
	return err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT b.id, b.name, b.owner_id, b.created_at, b.updated_at, b.current_plan_id, b.subscriptions_status, b.subscription_end_period, b.is_trial_used, b.current_subscription_id, b.is_offer_used,bm.user_id,bm.role,bm.current_balance 
FROM businesses b
JOIN
    business_members bm ON b.id = bm.business_id
WHERE bm.user_id = $1 and b.id = $2
`

type GetBusinessByIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetBusinessByIDRow struct {
	ID                    pgtype.UUID         `json:"id"`
	Name                  string              `json:"name"`
	OwnerID               pgtype.UUID         `json:"owner_id"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz  `json:"updated_at"`
	CurrentPlanID         pgtype.Text         `json:"current_plan_id"`
	SubscriptionsStatus   SubscriptionsStatus `json:"subscriptions_status"`
	SubscriptionEndPeriod pgtype.Timestamptz  `json:"subscription_end_period"`
	IsTrialUsed           bool                `json:"is_trial_used"`
	CurrentSubscriptionID pgtype.UUID         `json:"current_subscription_id"`
	IsOfferUsed           bool                `json:"is_offer_used"`
	UserID                pgtype.UUID         `json:"user_id"`
	Role                  BusinessRole        `json:"role"`
	CurrentBalance        pgtype.Numeric      `json:"current_balance"`
}

// Retrieves a single business record by its unique ID.
func (q *Queries) GetBusinessByID(ctx context.Context, arg GetBusinessByIDParams) (GetBusinessByIDRow, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, arg.UserID, arg.ID)
	var i GetBusinessByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentPlanID,
		&i.SubscriptionsStatus,
		&i.SubscriptionEndPeriod,
		&i.IsTrialUsed,
		&i.CurrentSubscriptionID,
		&i.IsOfferUsed,
		&i.UserID,
		&i.Role,
		&i.CurrentBalance,
	)
	return i, err
}

const getBusinessMembers = `-- name: GetBusinessMembers :many
SELECT u.id, u.name, u.email, u.phone_number, bm.role, bm.current_balance
FROM users u
JOIN business_members bm ON bm.user_id = u.id
WHERE bm.business_id = $1
ORDER BY u.name
`

type GetBusinessMembersRow struct {
	ID             pgtype.UUID    `json:"id"`
	Name           pgtype.Text    `json:"name"`
	Email          string         `json:"email"`
	PhoneNumber    pgtype.Text    `json:"phone_number"`
	Role           BusinessRole   `json:"role"`
	CurrentBalance pgtype.Numeric `json:"current_balance"`
}

// GetBusinessMembers returns all the particular business members
func (q *Queries) GetBusinessMembers(ctx context.Context, businessID pgtype.UUID) ([]GetBusinessMembersRow, error) {
	rows, err := q.db.Query(ctx, getBusinessMembers, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBusinessMembersRow{}
	for rows.Next() {
		var i GetBusinessMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.Role,
			&i.CurrentBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessesByOwnerID = `-- name: GetBusinessesByOwnerID :many
SELECT id, name, owner_id, created_at, updated_at, current_plan_id, subscriptions_status, subscription_end_period, is_trial_used, current_subscription_id, is_offer_used FROM businesses
WHERE owner_id = $1
`

// Retrieves all businesses owned by a specific user ID.
func (q *Queries) GetBusinessesByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, getBusinessesByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentPlanID,
			&i.SubscriptionsStatus,
			&i.SubscriptionEndPeriod,
			&i.IsTrialUsed,
			&i.CurrentSubscriptionID,
			&i.IsOfferUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessesByUserID = `-- name: GetBusinessesByUserID :many
SELECT 
    b.id, b.name, b.owner_id, b.created_at, b.updated_at, b.current_plan_id, b.subscriptions_status, b.subscription_end_period, b.is_trial_used, b.current_subscription_id, b.is_offer_used
    -- bm.role, 
    -- bm.current_balance
FROM 
    businesses b
JOIN 
    business_members bm ON b.id = bm.business_id
WHERE 
    bm.user_id = $1
`

// Retrieves all businesses a user is a member of, including their role and balance in each.
func (q *Queries) GetBusinessesByUserID(ctx context.Context, userID pgtype.UUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, getBusinessesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentPlanID,
			&i.SubscriptionsStatus,
			&i.SubscriptionEndPeriod,
			&i.IsTrialUsed,
			&i.CurrentSubscriptionID,
			&i.IsOfferUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberRole = `-- name: GetMemberRole :one
Select bm.role from business_members bm WHERE bm.user_id = $1 AND bm.business_id = $2
`

type GetMemberRoleParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// Based on userid and businessid it will return role
func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (BusinessRole, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.UserID, arg.BusinessID)
	var role BusinessRole
	err := row.Scan(&role)
	return role, err
}

const getMemberRoleBalance = `-- name: GetMemberRoleBalance :one
Select role, current_balance FROM business_members WHERE user_id = $1 AND business_id = $2
`

type GetMemberRoleBalanceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

type GetMemberRoleBalanceRow struct {
	Role           BusinessRole   `json:"role"`
	CurrentBalance pgtype.Numeric `json:"current_balance"`
}

// used to get a member details
func (q *Queries) GetMemberRoleBalance(ctx context.Context, arg GetMemberRoleBalanceParams) (GetMemberRoleBalanceRow, error) {
	row := q.db.QueryRow(ctx, getMemberRoleBalance, arg.UserID, arg.BusinessID)
	var i GetMemberRoleBalanceRow
	err := row.Scan(&i.Role, &i.CurrentBalance)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM business_members
WHERE user_id = $1 AND business_id = $2
`

type GetUserRoleParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// returns the role of the user
func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (BusinessRole, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.UserID, arg.BusinessID)
	var role BusinessRole
	err := row.Scan(&role)
	return role, err
}

const isUserMemberOfBusiness = `-- name: IsUserMemberOfBusiness :one
SELECT 1
FROM business_members
WHERE user_id = $1 AND business_id = $2
`

type IsUserMemberOfBusinessParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// returns 1 if a user is a member of the given businessId
func (q *Queries) IsUserMemberOfBusiness(ctx context.Context, arg IsUserMemberOfBusinessParams) (int32, error) {
	row := q.db.QueryRow(ctx, isUserMemberOfBusiness, arg.UserID, arg.BusinessID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE businesses
SET
  name = $2,
  updated_at = NOW()
WHERE
  id = $1
RETURNING id, name, owner_id, created_at, updated_at, current_plan_id, subscriptions_status, subscription_end_period, is_trial_used, current_subscription_id, is_offer_used
`

type UpdateBusinessParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusiness, arg.ID, arg.Name)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentPlanID,
		&i.SubscriptionsStatus,
		&i.SubscriptionEndPeriod,
		&i.IsTrialUsed,
		&i.CurrentSubscriptionID,
		&i.IsOfferUsed,
	)
	return i, err
}

const updateBusinessMember = `-- name: UpdateBusinessMember :one
UPDATE business_members
SET role = $1
WHERE user_id = $2 AND business_id = $3
RETURNING id, user_id, business_id, role, current_balance, created_at
`

type UpdateBusinessMemberParams struct {
	Role       BusinessRole `json:"role"`
	UserID     pgtype.UUID  `json:"user_id"`
	BusinessID pgtype.UUID  `json:"business_id"`
}

// used to update role in business_members
func (q *Queries) UpdateBusinessMember(ctx context.Context, arg UpdateBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, updateBusinessMember, arg.Role, arg.UserID, arg.BusinessID)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Role,
		&i.CurrentBalance,
		&i.CreatedAt,
	)
	return i, err
}

const updateBusinessMemberBalance = `-- name: UpdateBusinessMemberBalance :exec
UPDATE business_members
SET current_balance = current_balance + $1
WHERE user_id = $2 AND business_id = $3
`

type UpdateBusinessMemberBalanceParams struct {
	CurrentBalance pgtype.Numeric `json:"current_balance"`
	UserID         pgtype.UUID    `json:"user_id"`
	BusinessID     pgtype.UUID    `json:"business_id"`
}

// used to update balance in transactions
func (q *Queries) UpdateBusinessMemberBalance(ctx context.Context, arg UpdateBusinessMemberBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBusinessMemberBalance, arg.CurrentBalance, arg.UserID, arg.BusinessID)
	return err
}
