// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBusinessMember = `-- name: AddBusinessMember :one
INSERT INTO business_members (
    user_id,
    business_id,
    role
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, business_id, role, current_balance, created_at
`

type AddBusinessMemberParams struct {
	UserID     pgtype.UUID  `json:"user_id"`
	BusinessID pgtype.UUID  `json:"business_id"`
	Role       BusinessRole `json:"role"`
}

// Adds a user to a business with a specific role, returning the new membership record.
func (q *Queries) AddBusinessMember(ctx context.Context, arg AddBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, addBusinessMember, arg.UserID, arg.BusinessID, arg.Role)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Role,
		&i.CurrentBalance,
		&i.CreatedAt,
	)
	return i, err
}

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (
    name,
    owner_id
) VALUES (
    $1, $2
)
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateBusinessParams struct {
	Name    string      `json:"name"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

// Creates a new business with a specified name and owner ID, returning the new record.
func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness, arg.Name, arg.OwnerID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT id, name, owner_id, created_at, updated_at FROM businesses
WHERE id = $1
`

// Retrieves a single business record by its unique ID.
func (q *Queries) GetBusinessByID(ctx context.Context, id pgtype.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessesByOwnerID = `-- name: GetBusinessesByOwnerID :many
SELECT id, name, owner_id, created_at, updated_at FROM businesses
WHERE owner_id = $1
`

// Retrieves all businesses owned by a specific user ID.
func (q *Queries) GetBusinessesByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, getBusinessesByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessesByUserID = `-- name: GetBusinessesByUserID :many
SELECT 
    b.id, b.name, b.owner_id, b.created_at, b.updated_at, 
    bm.role, 
    bm.current_balance
FROM 
    businesses b
JOIN 
    business_members bm ON b.id = bm.business_id
WHERE 
    bm.user_id = $1
`

type GetBusinessesByUserIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Role           BusinessRole       `json:"role"`
	CurrentBalance pgtype.Numeric     `json:"current_balance"`
}

// Retrieves all businesses a user is a member of, including their role and balance in each.
func (q *Queries) GetBusinessesByUserID(ctx context.Context, userID pgtype.UUID) ([]GetBusinessesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getBusinessesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBusinessesByUserIDRow{}
	for rows.Next() {
		var i GetBusinessesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.CurrentBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
