// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO transaction_categories (
  business_id,
  name
) VALUES (
  $1, $2
)
RETURNING id, business_id, name, created_at, updated_at
`

type CreateCategoryParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Name       string      `json:"name"`
}

// add a new category
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (TransactionCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.BusinessID, arg.Name)
	var i TransactionCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM transaction_categories
WHERE id = $1 AND business_id = $2
RETURNING id
`

type DeleteCategoryParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// delete a particular category
func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCategory, arg.ID, arg.BusinessID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, business_id, name, created_at, updated_at FROM transaction_categories
WHERE id = $1 AND business_id = $2
`

type GetCategoryParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// get a particular category
func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (TransactionCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.BusinessID)
	var i TransactionCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByBusiness = `-- name: ListCategoriesByBusiness :many
SELECT id, business_id, name, created_at, updated_at FROM transaction_categories
WHERE business_id = $1
ORDER BY name ASC
`

// get all category that belongs to a business_id
func (q *Queries) ListCategoriesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]TransactionCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionCategory{}
	for rows.Next() {
		var i TransactionCategory
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE transaction_categories
SET
  name = $3,
  updated_at = now()
WHERE
  id = $1 AND business_id = $2
RETURNING id, business_id, name, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
	Name       string      `json:"name"`
}

// update a particular category
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (TransactionCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.BusinessID, arg.Name)
	var i TransactionCategory
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
