// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransactionCategory = `-- name: CreateTransactionCategory :one
INSERT INTO transaction_categories (
    business_id,
    name
) VALUES (
    $1, $2
) RETURNING id, business_id, name
`

type CreateTransactionCategoryParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Name       string      `json:"name"`
}

func (q *Queries) CreateTransactionCategory(ctx context.Context, arg CreateTransactionCategoryParams) (TransactionCategory, error) {
	row := q.db.QueryRow(ctx, createTransactionCategory, arg.BusinessID, arg.Name)
	var i TransactionCategory
	err := row.Scan(&i.ID, &i.BusinessID, &i.Name)
	return i, err
}

const deleteTransactionCategory = `-- name: DeleteTransactionCategory :exec
DELETE FROM transaction_categories
WHERE id = $1 AND business_id = $2
`

type DeleteTransactionCategoryParams struct {
	ID         int32       `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) DeleteTransactionCategory(ctx context.Context, arg DeleteTransactionCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteTransactionCategory, arg.ID, arg.BusinessID)
	return err
}

const getTransactionCategory = `-- name: GetTransactionCategory :one
SELECT id, business_id, name FROM transaction_categories
WHERE id = $1 AND business_id = $2
`

type GetTransactionCategoryParams struct {
	ID         int32       `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) GetTransactionCategory(ctx context.Context, arg GetTransactionCategoryParams) (TransactionCategory, error) {
	row := q.db.QueryRow(ctx, getTransactionCategory, arg.ID, arg.BusinessID)
	var i TransactionCategory
	err := row.Scan(&i.ID, &i.BusinessID, &i.Name)
	return i, err
}

const listTransactionCategories = `-- name: ListTransactionCategories :many
SELECT id, business_id, name FROM transaction_categories
WHERE business_id = $1
ORDER BY name
`

func (q *Queries) ListTransactionCategories(ctx context.Context, businessID pgtype.UUID) ([]TransactionCategory, error) {
	rows, err := q.db.Query(ctx, listTransactionCategories, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionCategory{}
	for rows.Next() {
		var i TransactionCategory
		if err := rows.Scan(&i.ID, &i.BusinessID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionCategory = `-- name: UpdateTransactionCategory :one
UPDATE transaction_categories
SET name = $2
WHERE id = $1 AND business_id = $3
RETURNING id, business_id, name
`

type UpdateTransactionCategoryParams struct {
	ID         int32       `json:"id"`
	Name       string      `json:"name"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) UpdateTransactionCategory(ctx context.Context, arg UpdateTransactionCategoryParams) (TransactionCategory, error) {
	row := q.db.QueryRow(ctx, updateTransactionCategory, arg.ID, arg.Name, arg.BusinessID)
	var i TransactionCategory
	err := row.Scan(&i.ID, &i.BusinessID, &i.Name)
	return i, err
}
