// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalStatus string

const (
	ApprovalStatusPending  ApprovalStatus = "pending"
	ApprovalStatusApproved ApprovalStatus = "approved"
	ApprovalStatusRejected ApprovalStatus = "rejected"
)

func (e *ApprovalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalStatus(s)
	case string:
		*e = ApprovalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalStatus: %T", src)
	}
	return nil
}

type NullApprovalStatus struct {
	ApprovalStatus ApprovalStatus `json:"approval_status"`
	Valid          bool           `json:"valid"` // Valid is true if ApprovalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalStatus), nil
}

type BusinessRole string

const (
	BusinessRoleCreator  BusinessRole = "creator"
	BusinessRoleAdmin    BusinessRole = "admin"
	BusinessRoleEmployee BusinessRole = "employee"
)

func (e *BusinessRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessRole(s)
	case string:
		*e = BusinessRole(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessRole: %T", src)
	}
	return nil
}

type NullBusinessRole struct {
	BusinessRole BusinessRole `json:"business_role"`
	Valid        bool         `json:"valid"` // Valid is true if BusinessRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessRole) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessRole), nil
}

type PartyType string

const (
	PartyTypeCustomer PartyType = "customer"
	PartyTypeSupplier PartyType = "supplier"
)

func (e *PartyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartyType(s)
	case string:
		*e = PartyType(s)
	default:
		return fmt.Errorf("unsupported scan type for PartyType: %T", src)
	}
	return nil
}

type NullPartyType struct {
	PartyType PartyType `json:"party_type"`
	Valid     bool      `json:"valid"` // Valid is true if PartyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartyType) Scan(value interface{}) error {
	if value == nil {
		ns.PartyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartyType), nil
}

type TransactionDirection string

const (
	TransactionDirectionIn      TransactionDirection = "in"
	TransactionDirectionOut     TransactionDirection = "out"
	TransactionDirectionDeposit TransactionDirection = "deposit"
)

func (e *TransactionDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionDirection(s)
	case string:
		*e = TransactionDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionDirection: %T", src)
	}
	return nil
}

type NullTransactionDirection struct {
	TransactionDirection TransactionDirection `json:"transaction_direction"`
	Valid                bool                 `json:"valid"` // Valid is true if TransactionDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionDirection) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionDirection), nil
}

type TransactionMode string

const (
	TransactionModeOnline TransactionMode = "online"
	TransactionModeCheck  TransactionMode = "check"
	TransactionModeCash   TransactionMode = "cash"
)

func (e *TransactionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionMode(s)
	case string:
		*e = TransactionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionMode: %T", src)
	}
	return nil
}

type NullTransactionMode struct {
	TransactionMode TransactionMode `json:"transaction_mode"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionMode) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionMode), nil
}

type Business struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BusinessMember struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	BusinessID     pgtype.UUID        `json:"business_id"`
	Role           BusinessRole       `json:"role"`
	CurrentBalance pgtype.Numeric     `json:"current_balance"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Party struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Type        PartyType          `json:"type"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	BusinessID  pgtype.UUID        `json:"business_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID          pgtype.UUID              `json:"id"`
	BusinessID  pgtype.UUID              `json:"business_id"`
	Amount      pgtype.Numeric           `json:"amount"`
	Description pgtype.Text              `json:"description"`
	PartyID     pgtype.UUID              `json:"party_id"`
	Mode        NullTransactionMode      `json:"mode"`
	Direction   NullTransactionDirection `json:"direction"`
	CategoryID  pgtype.Int4              `json:"category_id"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz       `json:"updated_at"`
}

type TransactionCategory struct {
	ID         int32       `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
	Name       string      `json:"name"`
}

type TransactionEditRequest struct {
	ID               pgtype.UUID        `json:"id"`
	TransactionID    pgtype.UUID        `json:"transaction_id"`
	RequestedByID    pgtype.UUID        `json:"requested_by_id"`
	ReviewedByID     pgtype.UUID        `json:"reviewed_by_id"`
	Status           ApprovalStatus     `json:"status"`
	RequestedChanges []byte             `json:"requested_changes"`
	Reason           pgtype.Text        `json:"reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Name        pgtype.Text        `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	GoogleID    string             `json:"google_id"`
	Picture     pgtype.Text        `json:"picture"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
