// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	GoogleID    string             `json:"google_id"`
	Email       string             `json:"email"`
	Name        pgtype.Text        `json:"name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Picture     pgtype.Text        `json:"picture"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
