// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID        `json:"id"`
	GoogleID    string             `json:"google_id"`
	Email       string             `json:"email"`
	Name        pgtype.Text        `json:"name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
