// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parties.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParty = `-- name: CreateParty :one
INSERT INTO parties (
  name,
  place,
  phone_number,
  business_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, place, phone_number, business_id, created_at, updated_at
`

type CreatePartyParams struct {
	Name        string      `json:"name"`
	Place       string      `json:"place"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	BusinessID  pgtype.UUID `json:"business_id"`
}

// add a party
func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty,
		arg.Name,
		arg.Place,
		arg.PhoneNumber,
		arg.BusinessID,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Place,
		&i.PhoneNumber,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParty = `-- name: DeleteParty :exec
DELETE FROM parties
WHERE id = $1
`

// delete a particular party
func (q *Queries) DeleteParty(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteParty, id)
	return err
}

const getParty = `-- name: GetParty :one
SELECT id, name, place, phone_number, business_id, created_at, updated_at FROM parties
WHERE id = $1
`

// get a particular party
func (q *Queries) GetParty(ctx context.Context, id pgtype.UUID) (Party, error) {
	row := q.db.QueryRow(ctx, getParty, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Place,
		&i.PhoneNumber,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPartiesByBusiness = `-- name: ListPartiesByBusiness :many
SELECT id, name, place, phone_number, business_id, created_at, updated_at FROM parties
WHERE business_id = $1
ORDER BY created_at DESC
`

// get all parties realated a particualr businessId
func (q *Queries) ListPartiesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]Party, error) {
	rows, err := q.db.Query(ctx, listPartiesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Party{}
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Place,
			&i.PhoneNumber,
			&i.BusinessID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartiesByBusinessAndPlace = `-- name: ListPartiesByBusinessAndPlace :many
SELECT id, name, place, phone_number, business_id, created_at, updated_at FROM parties
WHERE business_id = $1 AND place = $2
ORDER BY created_at DESC
`

type ListPartiesByBusinessAndPlaceParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Place      string      `json:"place"`
}

// get all parties realted a particular businessId and place
func (q *Queries) ListPartiesByBusinessAndPlace(ctx context.Context, arg ListPartiesByBusinessAndPlaceParams) ([]Party, error) {
	rows, err := q.db.Query(ctx, listPartiesByBusinessAndPlace, arg.BusinessID, arg.Place)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Party{}
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Place,
			&i.PhoneNumber,
			&i.BusinessID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniquePartyPlacesByBusiness = `-- name: ListUniquePartyPlacesByBusiness :many
SELECT DISTINCT place
FROM parties
WHERE business_id = $1
ORDER BY place ASC
`

// get all the unique places stored in parties table related to a businessId
func (q *Queries) ListUniquePartyPlacesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUniquePartyPlacesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var place string
		if err := rows.Scan(&place); err != nil {
			return nil, err
		}
		items = append(items, place)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParty = `-- name: UpdateParty :one
UPDATE parties
SET
  name = $2,
  place = $3,
  phone_number = $4,
  updated_at = now()
WHERE
  id = $1
RETURNING id, name, place, phone_number, business_id, created_at, updated_at
`

type UpdatePartyParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Place       string      `json:"place"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

// update a particular party
func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, updateParty,
		arg.ID,
		arg.Name,
		arg.Place,
		arg.PhoneNumber,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Place,
		&i.PhoneNumber,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
