// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parties.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParty = `-- name: CreateParty :one
INSERT INTO parties (
    business_id,
    name,
    type,
    phone_number
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, type, phone_number, business_id, created_at, updated_at
`

type CreatePartyParams struct {
	BusinessID  pgtype.UUID `json:"business_id"`
	Name        string      `json:"name"`
	Type        PartyType   `json:"type"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty,
		arg.BusinessID,
		arg.Name,
		arg.Type,
		arg.PhoneNumber,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.PhoneNumber,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParty = `-- name: DeleteParty :exec
DELETE FROM parties
WHERE id = $1 AND business_id = $2
`

type DeletePartyParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) DeleteParty(ctx context.Context, arg DeletePartyParams) error {
	_, err := q.db.Exec(ctx, deleteParty, arg.ID, arg.BusinessID)
	return err
}

const getParty = `-- name: GetParty :one
SELECT id, name, type, phone_number, business_id, created_at, updated_at FROM parties
WHERE id = $1 AND business_id = $2
`

type GetPartyParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) GetParty(ctx context.Context, arg GetPartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, getParty, arg.ID, arg.BusinessID)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.PhoneNumber,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParties = `-- name: ListParties :many
SELECT id, name, type, phone_number, business_id, created_at, updated_at FROM parties
WHERE business_id = $1
ORDER BY name
`

func (q *Queries) ListParties(ctx context.Context, businessID pgtype.UUID) ([]Party, error) {
	rows, err := q.db.Query(ctx, listParties, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Party{}
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.PhoneNumber,
			&i.BusinessID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartiesByType = `-- name: ListPartiesByType :many
SELECT id, name, type, phone_number, business_id, created_at, updated_at FROM parties
WHERE business_id = $1 AND type = $2
ORDER BY name
`

type ListPartiesByTypeParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Type       PartyType   `json:"type"`
}

func (q *Queries) ListPartiesByType(ctx context.Context, arg ListPartiesByTypeParams) ([]Party, error) {
	rows, err := q.db.Query(ctx, listPartiesByType, arg.BusinessID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Party{}
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.PhoneNumber,
			&i.BusinessID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParty = `-- name: UpdateParty :one
UPDATE parties
SET
    name = $2,
    type = $3,
    phone_number = $4
WHERE id = $1 AND business_id = $5
RETURNING id, name, type, phone_number, business_id, created_at, updated_at
`

type UpdatePartyParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Type        PartyType   `json:"type"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	BusinessID  pgtype.UUID `json:"business_id"`
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, updateParty,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.PhoneNumber,
		arg.BusinessID,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.PhoneNumber,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
