// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Adds a user to a business with a specific role, returning the new membership record.
	AddBusinessMember(ctx context.Context, arg AddBusinessMemberParams) (BusinessMember, error)
	CancelSubscription(ctx context.Context, razorpaySubscriptionID string) error
	// returns 1 if a user is admin or creator of a given business_id
	CheckAdmin(ctx context.Context, arg CheckAdminParams) (int32, error)
	// returns 1 if a user is a member of a given business_id
	CheckMember(ctx context.Context, arg CheckMemberParams) (int32, error)
	// CheckUserPlanEligibility checks if the user has free businesses
	// or trial period available
	CheckUserPlanEligibility(ctx context.Context, ownerID pgtype.UUID) (CheckUserPlanEligibilityRow, error)
	CreateBusinessAndAddOwner(ctx context.Context, arg CreateBusinessAndAddOwnerParams) (Business, error)
	// add a new category
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (TransactionCategory, error)
	CreateEditRequest(ctx context.Context, arg CreateEditRequestParams) (TransactionEditRequest, error)
	// Create the missing Invoice Query (we need this for the charged event)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (pgtype.UUID, error)
	// add a party
	CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error)
	// CreatePlan adds a new plan to plans table
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	// CreateSubscription creates new row in subscriptions table
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTransactionWithValidation(ctx context.Context, arg CreateTransactionWithValidationParams) (Transaction, error)
	// used to delete a business
	DeleteBusiness(ctx context.Context, id pgtype.UUID) error
	// used to remove business member
	DeleteBusinessMember(ctx context.Context, arg DeleteBusinessMemberParams) error
	// delete a particular category
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (pgtype.UUID, error)
	// delete a particular party
	DeleteParty(ctx context.Context, arg DeletePartyParams) (pgtype.UUID, error)
	// DeleteRefreshTokenByHash deletes a single refresh token by its hash.
	// This is used for logging out a single device.
	DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error
	// DeleteRefreshTokensByUserID deletes all refresh tokens for a specific user.
	// This is used for the "log out from all devices" feature.
	DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	// used to delete a transactions
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (DeleteTransactionRow, error)
	// Retrieves a single business record by its unique ID.
	GetBusinessByID(ctx context.Context, arg GetBusinessByIDParams) (GetBusinessByIDRow, error)
	// GetBusinessCurrentPlan gets the details on the current plan
	GetBusinessCurrentPlan(ctx context.Context, id pgtype.UUID) (GetBusinessCurrentPlanRow, error)
	// GetBusinessMembers returns all the particular business members
	GetBusinessMembers(ctx context.Context, businessID pgtype.UUID) ([]GetBusinessMembersRow, error)
	// Retrieves all businesses owned by a specific user ID.
	GetBusinessesByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Business, error)
	// Retrieves all businesses a user is a member of, including their role and balance in each.
	GetBusinessesByUserID(ctx context.Context, userID pgtype.UUID) ([]Business, error)
	// get a particular category
	GetCategory(ctx context.Context, arg GetCategoryParams) (TransactionCategory, error)
	// Based on userid and businessid it will return role
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (BusinessRole, error)
	// used to get a member details
	GetMemberRoleBalance(ctx context.Context, arg GetMemberRoleBalanceParams) (GetMemberRoleBalanceRow, error)
	// get a particular party
	GetParty(ctx context.Context, arg GetPartyParams) (Party, error)
	// GetPlan query gets plan based on the planId
	GetPlan(ctx context.Context, id string) (Plan, error)
	// GetRefreshTokenByHash finds a valid (non-expired) refresh token by its hash.
	// This is used during the /auth/refresh flow.
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error)
	// Query to find subscription by Razorpay ID (Critical for Webhooks)
	GetSubscriptionByRazorpayID(ctx context.Context, razorpaySubscriptionID string) (Subscription, error)
	GetSubscriptionStatus(ctx context.Context, arg GetSubscriptionStatusParams) (SubscriptionsStatus, error)
	// 1. Joins for REQUESTED changes (from JSON)
	// 2. NEW: Joins for ORIGINAL transaction (from Columns)
	GetTransactionApprovals(ctx context.Context, arg GetTransactionApprovalsParams) ([]GetTransactionApprovalsRow, error)
	// RETURNING id, created_at;
	GetTransactionForUpdate(ctx context.Context, arg GetTransactionForUpdateParams) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber pgtype.Text) (User, error)
	// returns the role of the user
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (BusinessRole, error)
	// InsertRefreshToken inserts a new refresh token into the database.
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	// returns 1 if a user is a member of the given businessId
	IsUserMemberOfBusiness(ctx context.Context, arg IsUserMemberOfBusinessParams) (int32, error)
	// get all category that belongs to a business_id
	ListCategoriesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]TransactionCategory, error)
	// get all parties realated a particualr businessId
	ListPartiesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]Party, error)
	// get all parties realted a particular businessId and place
	ListPartiesByBusinessAndPlace(ctx context.Context, arg ListPartiesByBusinessAndPlaceParams) ([]Party, error)
	// get all the unique places stored in parties table related to a businessId
	ListUniquePartyPlacesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]string, error)
	// get all active sessions/devices for a user
	ListUserDevices(ctx context.Context, userID pgtype.UUID) ([]ListUserDevicesRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Join Users
	// Join Requested Changes (from JSON)
	// NEW: Join Original Transaction
	PatchEditRequest(ctx context.Context, arg PatchEditRequestParams) (PatchEditRequestRow, error)
	UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error)
	// used to update role in business_members
	UpdateBusinessMember(ctx context.Context, arg UpdateBusinessMemberParams) (BusinessMember, error)
	// used to update balance in transactions
	UpdateBusinessMemberBalance(ctx context.Context, arg UpdateBusinessMemberBalanceParams) error
	// UpdateBusinessSubscription updates subscriptions related columns
	UpdateBusinessSubscription(ctx context.Context, arg UpdateBusinessSubscriptionParams) (Business, error)
	// update a particular category
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (TransactionCategory, error)
	// update a particular party
	UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error)
	UpdateStatusIfPending(ctx context.Context, arg UpdateStatusIfPendingParams) error
	// If 'is_trial_used' is already true, keep it true.
	UpdateSubscriptionAndBusiness(ctx context.Context, arg UpdateSubscriptionAndBusinessParams) error
	// Used for simple state changes like Paused, Resumed, Pending, Halted
	UpdateSubscriptionStatusRaw(ctx context.Context, arg UpdateSubscriptionStatusRawParams) error
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (UpsertUserByEmailRow, error)
	VerifyCategoryBelongsToBusiness(ctx context.Context, arg VerifyCategoryBelongsToBusinessParams) (bool, error)
	VerifyPartyBelongsToBusiness(ctx context.Context, arg VerifyPartyBelongsToBusinessParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
