// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Adds a user to a business with a specific role, returning the new membership record.
	AddBusinessMember(ctx context.Context, arg AddBusinessMemberParams) (BusinessMember, error)
	// returns 1 if a user is admin or creator of a given business_id
	CheckAdmin(ctx context.Context, arg CheckAdminParams) (int32, error)
	// returns 1 if a user is a member of a given business_id
	CheckMember(ctx context.Context, arg CheckMemberParams) (int32, error)
	CreateBusinessAndAddOwner(ctx context.Context, arg CreateBusinessAndAddOwnerParams) (Business, error)
	// add a new category
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (TransactionCategory, error)
	// add a party
	CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error)
	CreateTransactionWithValidation(ctx context.Context, arg CreateTransactionWithValidationParams) (Transaction, error)
	// used to delete a business
	DeleteBusiness(ctx context.Context, id pgtype.UUID) error
	// delete a particular category
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (pgtype.UUID, error)
	// delete a particular party
	DeleteParty(ctx context.Context, arg DeletePartyParams) (pgtype.UUID, error)
	// DeleteRefreshTokenByHash deletes a single refresh token by its hash.
	// This is used for logging out a single device.
	DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error
	// DeleteRefreshTokensByUserID deletes all refresh tokens for a specific user.
	// This is used for the "log out from all devices" feature.
	DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	// Retrieves a single business record by its unique ID.
	GetBusinessByID(ctx context.Context, arg GetBusinessByIDParams) (GetBusinessByIDRow, error)
	// GetBusinessMembers returns all the particular business members
	GetBusinessMembers(ctx context.Context, businessID pgtype.UUID) ([]GetBusinessMembersRow, error)
	// Retrieves all businesses owned by a specific user ID.
	GetBusinessesByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Business, error)
	// Retrieves all businesses a user is a member of, including their role and balance in each.
	GetBusinessesByUserID(ctx context.Context, userID pgtype.UUID) ([]Business, error)
	// get a particular category
	GetCategory(ctx context.Context, arg GetCategoryParams) (TransactionCategory, error)
	// Based on userid and businessid it will return role
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (BusinessRole, error)
	// get a particular party
	GetParty(ctx context.Context, arg GetPartyParams) (Party, error)
	// GetRefreshTokenByHash finds a valid (non-expired) refresh token by its hash.
	// This is used during the /auth/refresh flow.
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber pgtype.Text) (User, error)
	// returns the role of the user
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (BusinessRole, error)
	// InsertRefreshToken inserts a new refresh token into the database.
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	// returns 1 if a user is a member of the given businessId
	IsUserMemberOfBusiness(ctx context.Context, arg IsUserMemberOfBusinessParams) (int32, error)
	// get all category that belongs to a business_id
	ListCategoriesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]TransactionCategory, error)
	// get all parties realated a particualr businessId
	ListPartiesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]Party, error)
	// get all parties realted a particular businessId and place
	ListPartiesByBusinessAndPlace(ctx context.Context, arg ListPartiesByBusinessAndPlaceParams) ([]Party, error)
	// get all the unique places stored in parties table related to a businessId
	ListUniquePartyPlacesByBusiness(ctx context.Context, businessID pgtype.UUID) ([]string, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error)
	// used to update balance in transactions
	UpdateBusinessMemberBalance(ctx context.Context, arg UpdateBusinessMemberBalanceParams) error
	// update a particular category
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (TransactionCategory, error)
	// update a particular party
	UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (UpsertUserByEmailRow, error)
	VerifyCategoryBelongsToBusiness(ctx context.Context, arg VerifyCategoryBelongsToBusinessParams) (bool, error)
	VerifyPartyBelongsToBusiness(ctx context.Context, arg VerifyPartyBelongsToBusinessParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
