// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refreshToken.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

// DeleteRefreshTokenByHash deletes a single refresh token by its hash.
// This is used for logging out a single device.
func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

// DeleteRefreshTokensByUserID deletes all refresh tokens for a specific user.
// This is used for the "log out from all devices" feature.
func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, expires_at, device_info, created_at
FROM refresh_tokens
WHERE token_hash = $1 AND expires_at > NOW()
`

type GetRefreshTokenByHashRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// GetRefreshTokenByHash finds a valid (non-expired) refresh token by its hash.
// This is used during the /auth/refresh flow.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.DeviceInfo,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token_hash,
    expires_at,
    device_info
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, token_hash, expires_at, device_info, created_at
`

type InsertRefreshTokenParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	DeviceInfo pgtype.Text        `json:"device_info"`
}

// InsertRefreshToken inserts a new refresh token into the database.
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.DeviceInfo,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.DeviceInfo,
		&i.CreatedAt,
	)
	return i, err
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT 
    id, 
    device_info, 
    created_at, 
    expires_at 
FROM refresh_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListUserDevicesRow struct {
	ID         pgtype.UUID        `json:"id"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// get all active sessions/devices for a user
func (q *Queries) ListUserDevices(ctx context.Context, userID pgtype.UUID) ([]ListUserDevicesRow, error) {
	rows, err := q.db.Query(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDevicesRow{}
	for rows.Next() {
		var i ListUserDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceInfo,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
