// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserPlanEligibility = `-- name: CheckUserPlanEligibility :one
SELECT 
    -- Logic: If count of 'free' plans is 0, then Free IS available.
    (COUNT(*) FILTER (WHERE current_plan_id = 'free') = 0)::BOOLEAN AS free_available,
    
    -- Logic: If count of businesses that used a trial is 0, then Trial IS available.
    (COUNT(*) FILTER (WHERE is_trial_used = true) = 0)::BOOLEAN AS trial_available
FROM businesses
WHERE owner_id = $1
`

type CheckUserPlanEligibilityRow struct {
	FreeAvailable  bool `json:"free_available"`
	TrialAvailable bool `json:"trial_available"`
}

// CheckUserPlanEligibility checks if the user has free businesses
// or trial period available
func (q *Queries) CheckUserPlanEligibility(ctx context.Context, ownerID pgtype.UUID) (CheckUserPlanEligibilityRow, error) {
	row := q.db.QueryRow(ctx, checkUserPlanEligibility, ownerID)
	var i CheckUserPlanEligibilityRow
	err := row.Scan(&i.FreeAvailable, &i.TrialAvailable)
	return i, err
}

const getBusinessCurrentPlan = `-- name: GetBusinessCurrentPlan :one
SELECT 
    b.current_plan_id,
    p.name AS plan_name,
    p.amount,
    p.currency,
    b.subscriptions_status,
    b.subscription_end_date,
    (
        SELECT COUNT(*)::INT 
        FROM business_members bm 
        WHERE bm.business_id = b.id
    ) AS members_count
FROM businesses b
LEFT JOIN plans p ON b.current_plan_id = p.id
WHERE b.id = $1
`

type GetBusinessCurrentPlanRow struct {
	CurrentPlanID       pgtype.Text             `json:"current_plan_id"`
	PlanName            pgtype.Text             `json:"plan_name"`
	Amount              pgtype.Int8             `json:"amount"`
	Currency            pgtype.Text             `json:"currency"`
	SubscriptionsStatus NullSubscriptionsStatus `json:"subscriptions_status"`
	SubscriptionEndDate pgtype.Timestamptz      `json:"subscription_end_date"`
	MembersCount        int32                   `json:"members_count"`
}

// GetBusinessCurrentPlan gets the details on the current plan
func (q *Queries) GetBusinessCurrentPlan(ctx context.Context, id pgtype.UUID) (GetBusinessCurrentPlanRow, error) {
	row := q.db.QueryRow(ctx, getBusinessCurrentPlan, id)
	var i GetBusinessCurrentPlanRow
	err := row.Scan(
		&i.CurrentPlanID,
		&i.PlanName,
		&i.Amount,
		&i.Currency,
		&i.SubscriptionsStatus,
		&i.SubscriptionEndDate,
		&i.MembersCount,
	)
	return i, err
}
