// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMarketerCommission = `-- name: AddMarketerCommission :exec
UPDATE marketers
SET 
    commission_balance = commission_balance + $2,
    total_commission = total_commission + $2,
    updated_at = now()
WHERE id = $1
`

type AddMarketerCommissionParams struct {
	ID     pgtype.UUID `json:"id"`
	Amount int64       `json:"amount"`
}

func (q *Queries) AddMarketerCommission(ctx context.Context, arg AddMarketerCommissionParams) error {
	_, err := q.db.Exec(ctx, addMarketerCommission, arg.ID, arg.Amount)
	return err
}

const cancelSubscription = `-- name: CancelSubscription :exec
WITH updated_sub AS (
    UPDATE subscriptions
    SET 
        status = 'canceled',
        current_period_end = now(), -- Cut off access immediately (or keep date if you prefer)
        updated_at = now()
    WHERE razorpay_subscription_id = $1
    RETURNING id, business_id
)
UPDATE businesses
SET 
    subscriptions_status = 'canceled',
    current_subscription_id = NULL -- Unlink the cancelled sub
FROM updated_sub
WHERE businesses.id = updated_sub.business_id
  -- SAFETY: Only cancel business status if this was the CURRENT active subscription
  AND businesses.current_subscription_id = updated_sub.id
`

func (q *Queries) CancelSubscription(ctx context.Context, razorpaySubscriptionID string) error {
	_, err := q.db.Exec(ctx, cancelSubscription, razorpaySubscriptionID)
	return err
}

const checkUserPlanEligibility = `-- name: CheckUserPlanEligibility :one
SELECT 
    -- Logic: If count of 'free' plans is 0, then Free IS available.
    (COUNT(*) FILTER (WHERE current_plan_id = 'permanent-solo-0') = 0)::BOOLEAN AS free_available,
    
    -- Logic: If count of businesses that used a trial is 0, then Trial IS available.
    (COUNT(*) FILTER (WHERE is_trial_used = true) = 0)::BOOLEAN AS trial_available
FROM businesses
WHERE owner_id = $1
`

type CheckUserPlanEligibilityRow struct {
	FreeAvailable  bool `json:"free_available"`
	TrialAvailable bool `json:"trial_available"`
}

// CheckUserPlanEligibility checks if the user has free businesses
// or trial period available
func (q *Queries) CheckUserPlanEligibility(ctx context.Context, ownerID pgtype.UUID) (CheckUserPlanEligibilityRow, error) {
	row := q.db.QueryRow(ctx, checkUserPlanEligibility, ownerID)
	var i CheckUserPlanEligibilityRow
	err := row.Scan(&i.FreeAvailable, &i.TrialAvailable)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO subscription_invoices (
  subscription_id, business_id, razorpay_payment_id, amount_paid, currency, status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT DO NOTHING 
RETURNING id
`

type CreateInvoiceParams struct {
	SubscriptionID    pgtype.UUID                `json:"subscription_id"`
	BusinessID        pgtype.UUID                `json:"business_id"`
	RazorpayPaymentID string                     `json:"razorpay_payment_id"`
	AmountPaid        int64                      `json:"amount_paid"`
	Currency          pgtype.Text                `json:"currency"`
	Status            SubscriptionInvoicesStatus `json:"status"`
}

// Create the missing Invoice Query (we need this for the charged event)
func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.SubscriptionID,
		arg.BusinessID,
		arg.RazorpayPaymentID,
		arg.AmountPaid,
		arg.Currency,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
  id,
  razorpay_plan_id,
  name,
  description,
  amount,
  currency,
  user_limit,
  period,
  active
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING id, razorpay_plan_id, name, description, amount, currency, user_limit, period, active, created_at
`

type CreatePlanParams struct {
	ID             string      `json:"id"`
	RazorpayPlanID string      `json:"razorpay_plan_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	Amount         int64       `json:"amount"`
	Currency       string      `json:"currency"`
	UserLimit      int32       `json:"user_limit"`
	Period         PlansPeriod `json:"period"`
	Active         pgtype.Bool `json:"active"`
}

// CreatePlan adds a new plan to plans table
func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ID,
		arg.RazorpayPlanID,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.UserLimit,
		arg.Period,
		arg.Active,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.RazorpayPlanID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.UserLimit,
		&i.Period,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    business_id,
    plan_id,
    razorpay_subscription_id,
    status,
    marketer_id,
    is_offer_applied
) VALUES (
    $1, $2, $3,$4, $5, $6
) RETURNING id, business_id, plan_id, marketer_id, razorpay_subscription_id, current_period_start, current_period_end, status, is_offer_applied, created_at, updated_at
`

type CreateSubscriptionParams struct {
	BusinessID             pgtype.UUID         `json:"business_id"`
	PlanID                 string              `json:"plan_id"`
	RazorpaySubscriptionID string              `json:"razorpay_subscription_id"`
	Status                 SubscriptionsStatus `json:"status"`
	MarketerID             pgtype.UUID         `json:"marketer_id"`
	IsOfferApplied         bool                `json:"is_offer_applied"`
}

// CreateSubscription creates new row in subscriptions table
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.BusinessID,
		arg.PlanID,
		arg.RazorpaySubscriptionID,
		arg.Status,
		arg.MarketerID,
		arg.IsOfferApplied,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.PlanID,
		&i.MarketerID,
		&i.RazorpaySubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.Status,
		&i.IsOfferApplied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessCurrentPlan = `-- name: GetBusinessCurrentPlan :one
SELECT 
    b.current_plan_id,
    p.name AS plan_name,
    p.amount,
    p.currency,
    b.subscriptions_status,
    b.subscription_end_period,
    b.is_trial_used,
    b.offer_code,
    
    -- Fetch directly from the joined subscription table
    s.id AS subscription_id,
    s.razorpay_subscription_id,
    s.marketer_id,    
    (
        SELECT COUNT(*)::INT 
        FROM business_members bm 
        WHERE bm.business_id = b.id
    ) AS members_count
FROM businesses b
LEFT JOIN plans p ON b.current_plan_id = p.id
LEFT JOIN subscriptions s ON b.current_subscription_id = s.id
WHERE b.id = $1
`

type GetBusinessCurrentPlanRow struct {
	CurrentPlanID          pgtype.Text         `json:"current_plan_id"`
	PlanName               pgtype.Text         `json:"plan_name"`
	Amount                 pgtype.Int8         `json:"amount"`
	Currency               pgtype.Text         `json:"currency"`
	SubscriptionsStatus    SubscriptionsStatus `json:"subscriptions_status"`
	SubscriptionEndPeriod  pgtype.Timestamptz  `json:"subscription_end_period"`
	IsTrialUsed            bool                `json:"is_trial_used"`
	OfferCode              pgtype.Text         `json:"offer_code"`
	SubscriptionID         pgtype.UUID         `json:"subscription_id"`
	RazorpaySubscriptionID pgtype.Text         `json:"razorpay_subscription_id"`
	MarketerID             pgtype.UUID         `json:"marketer_id"`
	MembersCount           int32               `json:"members_count"`
}

// GetBusinessCurrentPlan gets the details on the current plan
func (q *Queries) GetBusinessCurrentPlan(ctx context.Context, id pgtype.UUID) (GetBusinessCurrentPlanRow, error) {
	row := q.db.QueryRow(ctx, getBusinessCurrentPlan, id)
	var i GetBusinessCurrentPlanRow
	err := row.Scan(
		&i.CurrentPlanID,
		&i.PlanName,
		&i.Amount,
		&i.Currency,
		&i.SubscriptionsStatus,
		&i.SubscriptionEndPeriod,
		&i.IsTrialUsed,
		&i.OfferCode,
		&i.SubscriptionID,
		&i.RazorpaySubscriptionID,
		&i.MarketerID,
		&i.MembersCount,
	)
	return i, err
}

const getMarketerById = `-- name: GetMarketerById :one
SELECT id, name, email, password_hash, offer_code_upi, razorpay_offer_id_upi, offer_code_card, razorpay_offer_id_card, offer_code_life, razorpay_offer_id_life, discount_percent, commission_percent, commission_balance, total_commission, created_at, updated_at FROM marketers WHERE id = $1
`

func (q *Queries) GetMarketerById(ctx context.Context, id pgtype.UUID) (Marketer, error) {
	row := q.db.QueryRow(ctx, getMarketerById, id)
	var i Marketer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.OfferCodeUpi,
		&i.RazorpayOfferIDUpi,
		&i.OfferCodeCard,
		&i.RazorpayOfferIDCard,
		&i.OfferCodeLife,
		&i.RazorpayOfferIDLife,
		&i.DiscountPercent,
		&i.CommissionPercent,
		&i.CommissionBalance,
		&i.TotalCommission,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferDetailsByCode = `-- name: GetOfferDetailsByCode :one
SELECT 
    id, 
    commission_percent,
    discount_percent,
    CASE 
        WHEN offer_code_upi  = $1 THEN razorpay_offer_id_upi
        WHEN offer_code_card = $1 THEN razorpay_offer_id_card
        WHEN offer_code_life = $1 THEN razorpay_offer_id_life
    END::text AS razorpay_offer_id
FROM marketers
WHERE offer_code_upi = $1 
   OR offer_code_card = $1 
   OR offer_code_life = $1
`

type GetOfferDetailsByCodeRow struct {
	ID                pgtype.UUID `json:"id"`
	CommissionPercent int32       `json:"commission_percent"`
	DiscountPercent   int32       `json:"discount_percent"`
	RazorpayOfferID   string      `json:"razorpay_offer_id"`
}

// ********************************************************************************************************************
// offers related
// ********************************************************************************************************************
func (q *Queries) GetOfferDetailsByCode(ctx context.Context, code string) (GetOfferDetailsByCodeRow, error) {
	row := q.db.QueryRow(ctx, getOfferDetailsByCode, code)
	var i GetOfferDetailsByCodeRow
	err := row.Scan(
		&i.ID,
		&i.CommissionPercent,
		&i.DiscountPercent,
		&i.RazorpayOfferID,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, razorpay_plan_id, name, description, amount, currency, user_limit, period, active, created_at FROM plans WHERE id = $1
`

// GetPlan query gets plan based on the planId
func (q *Queries) GetPlan(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.RazorpayPlanID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.UserLimit,
		&i.Period,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByRazorpayID = `-- name: GetSubscriptionByRazorpayID :one
SELECT id, business_id, plan_id, marketer_id, razorpay_subscription_id, current_period_start, current_period_end, status, is_offer_applied, created_at, updated_at FROM subscriptions WHERE razorpay_subscription_id = $1 LIMIT 1
`

// Query to find subscription by Razorpay ID (Critical for Webhooks)
func (q *Queries) GetSubscriptionByRazorpayID(ctx context.Context, razorpaySubscriptionID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByRazorpayID, razorpaySubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.PlanID,
		&i.MarketerID,
		&i.RazorpaySubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.Status,
		&i.IsOfferApplied,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionStatus = `-- name: GetSubscriptionStatus :one
SELECT status FROM subscriptions WHERE business_id = $1 AND id = $2
`

type GetSubscriptionStatusParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) GetSubscriptionStatus(ctx context.Context, arg GetSubscriptionStatusParams) (SubscriptionsStatus, error) {
	row := q.db.QueryRow(ctx, getSubscriptionStatus, arg.BusinessID, arg.ID)
	var status SubscriptionsStatus
	err := row.Scan(&status)
	return status, err
}

const updateBusinessSubscription = `-- name: UpdateBusinessSubscription :one
UPDATE businesses
SET 
    current_plan_id = $2,
    subscriptions_status = $3,
    subscription_end_period = $4,
    -- If 'is_trial_used' is already true, keep it true.
    -- If input is true, make it true.
    -- Only if BOTH are false does it stay false.
    is_trial_used = (is_trial_used OR COALESCE($6::boolean, false)),
    is_offer_used = (is_offer_used OR COALESCE($7::boolean, false)),
    current_subscription_id = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, current_plan_id, subscriptions_status, subscription_end_period, is_trial_used, current_subscription_id, is_offer_used, offer_code
`

type UpdateBusinessSubscriptionParams struct {
	ID                    pgtype.UUID         `json:"id"`
	CurrentPlanID         pgtype.Text         `json:"current_plan_id"`
	SubscriptionsStatus   SubscriptionsStatus `json:"subscriptions_status"`
	SubscriptionEndPeriod pgtype.Timestamptz  `json:"subscription_end_period"`
	CurrentSubscriptionID pgtype.UUID         `json:"current_subscription_id"`
	IsTrialUsed           pgtype.Bool         `json:"is_trial_used"`
	IsOfferUsed           pgtype.Bool         `json:"is_offer_used"`
}

// UpdateBusinessSubscription updates subscriptions related columns
func (q *Queries) UpdateBusinessSubscription(ctx context.Context, arg UpdateBusinessSubscriptionParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusinessSubscription,
		arg.ID,
		arg.CurrentPlanID,
		arg.SubscriptionsStatus,
		arg.SubscriptionEndPeriod,
		arg.CurrentSubscriptionID,
		arg.IsTrialUsed,
		arg.IsOfferUsed,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentPlanID,
		&i.SubscriptionsStatus,
		&i.SubscriptionEndPeriod,
		&i.IsTrialUsed,
		&i.CurrentSubscriptionID,
		&i.IsOfferUsed,
		&i.OfferCode,
	)
	return i, err
}

const updateStatusIfPending = `-- name: UpdateStatusIfPending :exec
WITH updated_sub AS (
    UPDATE subscriptions
    SET 
        status = $2,
        -- Use sqlc.narg to handle optional End Date updates (for Trials)
        current_period_end = COALESCE($4::TIMESTAMPTZ, current_period_end),
        updated_at = now()
    WHERE razorpay_subscription_id = $1
      -- ✅ ATOMIC GUARD: Only allow update if we are in "start" states
      AND status::text IN ('inactive', 'pending', 'trialing_pending', 'authenticated')
    RETURNING id, business_id, status, current_period_end,plan_id
)
UPDATE businesses
SET 
    subscriptions_status = updated_sub.status,
    subscription_end_period = updated_sub.current_period_end,
    current_plan_id = updated_sub.plan_id,
    current_subscription_id = updated_sub.id,
    is_trial_used = (is_trial_used OR COALESCE($3::boolean, false))
FROM updated_sub
WHERE businesses.id = updated_sub.business_id
`

type UpdateStatusIfPendingParams struct {
	RazorpaySubscriptionID string              `json:"razorpay_subscription_id"`
	Status                 SubscriptionsStatus `json:"status"`
	IsTrialUsed            pgtype.Bool         `json:"is_trial_used"`
	CurrentPeriodEnd       pgtype.Timestamptz  `json:"current_period_end"`
}

func (q *Queries) UpdateStatusIfPending(ctx context.Context, arg UpdateStatusIfPendingParams) error {
	_, err := q.db.Exec(ctx, updateStatusIfPending,
		arg.RazorpaySubscriptionID,
		arg.Status,
		arg.IsTrialUsed,
		arg.CurrentPeriodEnd,
	)
	return err
}

const updateSubscriptionAndBusiness = `-- name: UpdateSubscriptionAndBusiness :exec
WITH updated_sub AS (
    UPDATE subscriptions
    SET 
        status = $2,
        current_period_start = $3,
        current_period_end = $4,
        updated_at = now()
    WHERE razorpay_subscription_id = $1
    RETURNING id, business_id, status, current_period_end, plan_id, is_offer_applied
)
UPDATE businesses
SET 
    current_plan_id = updated_sub.plan_id,
    subscriptions_status = updated_sub.status,
    subscription_end_period = updated_sub.current_period_end,
    current_subscription_id = updated_sub.id,
    
    -- Trial Logic
    is_trial_used = (is_trial_used OR COALESCE($5::boolean, false)),
    
    -- Offer Logic
    is_offer_used = (is_offer_used OR updated_sub.is_offer_applied),
    
    -- Use narg. If input is NULL, COALESCE keeps the old value.
    offer_code = COALESCE($6::text, offer_code)

FROM updated_sub
WHERE businesses.id = updated_sub.business_id
`

type UpdateSubscriptionAndBusinessParams struct {
	RazorpaySubscriptionID string              `json:"razorpay_subscription_id"`
	Status                 SubscriptionsStatus `json:"status"`
	CurrentPeriodStart     pgtype.Timestamptz  `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz  `json:"current_period_end"`
	IsTrialUsed            pgtype.Bool         `json:"is_trial_used"`
	OfferCode              pgtype.Text         `json:"offer_code"`
}

func (q *Queries) UpdateSubscriptionAndBusiness(ctx context.Context, arg UpdateSubscriptionAndBusinessParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionAndBusiness,
		arg.RazorpaySubscriptionID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.IsTrialUsed,
		arg.OfferCode,
	)
	return err
}

const updateSubscriptionStatusRaw = `-- name: UpdateSubscriptionStatusRaw :exec
WITH updated_sub AS (
    UPDATE subscriptions
    SET 
        status = $2,
        updated_at = now()
    WHERE razorpay_subscription_id = $1
    RETURNING id, business_id, status
)
UPDATE businesses
SET 
    subscriptions_status = updated_sub.status
FROM updated_sub
WHERE businesses.id = updated_sub.business_id
`

type UpdateSubscriptionStatusRawParams struct {
	RazorpaySubscriptionID string              `json:"razorpay_subscription_id"`
	Status                 SubscriptionsStatus `json:"status"`
}

// Used for simple state changes like Paused, Resumed, Pending, Halted
func (q *Queries) UpdateSubscriptionStatusRaw(ctx context.Context, arg UpdateSubscriptionStatusRawParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatusRaw, arg.RazorpaySubscriptionID, arg.Status)
	return err
}
