// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    business_id,
    amount,
    direction,
    description,
    party_id,
    mode,
    category_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, business_id, amount, description, party_id, mode, direction, category_id, created_at, updated_at
`

type CreateTransactionParams struct {
	BusinessID  pgtype.UUID              `json:"business_id"`
	Amount      pgtype.Numeric           `json:"amount"`
	Direction   NullTransactionDirection `json:"direction"`
	Description pgtype.Text              `json:"description"`
	PartyID     pgtype.UUID              `json:"party_id"`
	Mode        NullTransactionMode      `json:"mode"`
	CategoryID  pgtype.Int4              `json:"category_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.BusinessID,
		arg.Amount,
		arg.Direction,
		arg.Description,
		arg.PartyID,
		arg.Mode,
		arg.CategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Amount,
		&i.Description,
		&i.PartyID,
		&i.Mode,
		&i.Direction,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionEditRequest = `-- name: CreateTransactionEditRequest :one

INSERT INTO transaction_edit_requests (
    transaction_id,
    requested_by_id,
    requested_changes,
    reason
) VALUES (
    $1, $2, $3, $4
) RETURNING id, transaction_id, requested_by_id, reviewed_by_id, status, requested_changes, reason, created_at, updated_at
`

type CreateTransactionEditRequestParams struct {
	TransactionID    pgtype.UUID `json:"transaction_id"`
	RequestedByID    pgtype.UUID `json:"requested_by_id"`
	RequestedChanges []byte      `json:"requested_changes"`
	Reason           pgtype.Text `json:"reason"`
}

// --- Transaction Edit Requests ---
func (q *Queries) CreateTransactionEditRequest(ctx context.Context, arg CreateTransactionEditRequestParams) (TransactionEditRequest, error) {
	row := q.db.QueryRow(ctx, createTransactionEditRequest,
		arg.TransactionID,
		arg.RequestedByID,
		arg.RequestedChanges,
		arg.Reason,
	)
	var i TransactionEditRequest
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.RequestedByID,
		&i.ReviewedByID,
		&i.Status,
		&i.RequestedChanges,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1 AND business_id = $2
`

type DeleteTransactionParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.BusinessID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, business_id, amount, description, party_id, mode, direction, category_id, created_at, updated_at FROM transactions
WHERE id = $1 AND business_id = $2
`

type GetTransactionParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.BusinessID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Amount,
		&i.Description,
		&i.PartyID,
		&i.Mode,
		&i.Direction,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionEditRequest = `-- name: GetTransactionEditRequest :one
SELECT id, transaction_id, requested_by_id, reviewed_by_id, status, requested_changes, reason, created_at, updated_at FROM transaction_edit_requests
WHERE id = $1
`

func (q *Queries) GetTransactionEditRequest(ctx context.Context, id pgtype.UUID) (TransactionEditRequest, error) {
	row := q.db.QueryRow(ctx, getTransactionEditRequest, id)
	var i TransactionEditRequest
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.RequestedByID,
		&i.ReviewedByID,
		&i.Status,
		&i.RequestedChanges,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionRich = `-- name: GetTransactionRich :one
SELECT
    t.id, t.business_id, t.amount, t.description, t.party_id, t.mode, t.direction, t.category_id, t.created_at, t.updated_at,
    p.name AS party_name,
    tc.name AS category_name
FROM
    transactions t
LEFT JOIN
    parties p ON t.party_id = p.id
LEFT JOIN
    transaction_categories tc ON t.category_id = tc.id
WHERE
    t.id = $1 AND t.business_id = $2
`

type GetTransactionRichParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

type GetTransactionRichRow struct {
	ID           pgtype.UUID              `json:"id"`
	BusinessID   pgtype.UUID              `json:"business_id"`
	Amount       pgtype.Numeric           `json:"amount"`
	Description  pgtype.Text              `json:"description"`
	PartyID      pgtype.UUID              `json:"party_id"`
	Mode         NullTransactionMode      `json:"mode"`
	Direction    NullTransactionDirection `json:"direction"`
	CategoryID   pgtype.Int4              `json:"category_id"`
	CreatedAt    pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz       `json:"updated_at"`
	PartyName    pgtype.Text              `json:"party_name"`
	CategoryName pgtype.Text              `json:"category_name"`
}

// Gets a single transaction with party and category names
func (q *Queries) GetTransactionRich(ctx context.Context, arg GetTransactionRichParams) (GetTransactionRichRow, error) {
	row := q.db.QueryRow(ctx, getTransactionRich, arg.ID, arg.BusinessID)
	var i GetTransactionRichRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Amount,
		&i.Description,
		&i.PartyID,
		&i.Mode,
		&i.Direction,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartyName,
		&i.CategoryName,
	)
	return i, err
}

const listEditRequestsForTransaction = `-- name: ListEditRequestsForTransaction :many
SELECT id, transaction_id, requested_by_id, reviewed_by_id, status, requested_changes, reason, created_at, updated_at FROM transaction_edit_requests
WHERE transaction_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEditRequestsForTransaction(ctx context.Context, transactionID pgtype.UUID) ([]TransactionEditRequest, error) {
	rows, err := q.db.Query(ctx, listEditRequestsForTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionEditRequest{}
	for rows.Next() {
		var i TransactionEditRequest
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.RequestedByID,
			&i.ReviewedByID,
			&i.Status,
			&i.RequestedChanges,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEditRequestsForBusiness = `-- name: ListPendingEditRequestsForBusiness :many
SELECT ter.id, ter.transaction_id, ter.requested_by_id, ter.reviewed_by_id, ter.status, ter.requested_changes, ter.reason, ter.created_at, ter.updated_at
FROM transaction_edit_requests ter
JOIN transactions t ON ter.transaction_id = t.id
WHERE
    t.business_id = $1
    AND ter.status = 'pending'
ORDER BY
    ter.created_at ASC
`

func (q *Queries) ListPendingEditRequestsForBusiness(ctx context.Context, businessID pgtype.UUID) ([]TransactionEditRequest, error) {
	rows, err := q.db.Query(ctx, listPendingEditRequestsForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionEditRequest{}
	for rows.Next() {
		var i TransactionEditRequest
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.RequestedByID,
			&i.ReviewedByID,
			&i.Status,
			&i.RequestedChanges,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id, t.business_id, t.amount, t.description, t.party_id, t.mode, t.direction, t.category_id, t.created_at, t.updated_at,
    p.name AS party_name,
    tc.name AS category_name
FROM
    transactions t
LEFT JOIN
    parties p ON t.party_id = p.id
LEFT JOIN
    transaction_categories tc ON t.category_id = tc.id
WHERE
    t.business_id = $1
ORDER BY
    t.created_at DESC
LIMIT $2
OFFSET $3
`

type ListTransactionsParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListTransactionsRow struct {
	ID           pgtype.UUID              `json:"id"`
	BusinessID   pgtype.UUID              `json:"business_id"`
	Amount       pgtype.Numeric           `json:"amount"`
	Description  pgtype.Text              `json:"description"`
	PartyID      pgtype.UUID              `json:"party_id"`
	Mode         NullTransactionMode      `json:"mode"`
	Direction    NullTransactionDirection `json:"direction"`
	CategoryID   pgtype.Int4              `json:"category_id"`
	CreatedAt    pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz       `json:"updated_at"`
	PartyName    pgtype.Text              `json:"party_name"`
	CategoryName pgtype.Text              `json:"category_name"`
}

// This query joins parties and categories to get their names
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Amount,
			&i.Description,
			&i.PartyID,
			&i.Mode,
			&i.Direction,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PartyName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEditRequestStatus = `-- name: UpdateEditRequestStatus :one
UPDATE transaction_edit_requests
SET
    status = $2,
    reviewed_by_id = $3,
    updated_at = now()
WHERE
    id = $1
RETURNING id, transaction_id, requested_by_id, reviewed_by_id, status, requested_changes, reason, created_at, updated_at
`

type UpdateEditRequestStatusParams struct {
	ID           pgtype.UUID    `json:"id"`
	Status       ApprovalStatus `json:"status"`
	ReviewedByID pgtype.UUID    `json:"reviewed_by_id"`
}

func (q *Queries) UpdateEditRequestStatus(ctx context.Context, arg UpdateEditRequestStatusParams) (TransactionEditRequest, error) {
	row := q.db.QueryRow(ctx, updateEditRequestStatus, arg.ID, arg.Status, arg.ReviewedByID)
	var i TransactionEditRequest
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.RequestedByID,
		&i.ReviewedByID,
		&i.Status,
		&i.RequestedChanges,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    amount = $2,
    direction = $3,
    description = $4,
    party_id = $5,
    mode = $6,
    category_id = $7,
    updated_at = now()
WHERE id = $1 AND business_id = $8
RETURNING id, business_id, amount, description, party_id, mode, direction, category_id, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          pgtype.UUID              `json:"id"`
	Amount      pgtype.Numeric           `json:"amount"`
	Direction   NullTransactionDirection `json:"direction"`
	Description pgtype.Text              `json:"description"`
	PartyID     pgtype.UUID              `json:"party_id"`
	Mode        NullTransactionMode      `json:"mode"`
	CategoryID  pgtype.Int4              `json:"category_id"`
	BusinessID  pgtype.UUID              `json:"business_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Amount,
		arg.Direction,
		arg.Description,
		arg.PartyID,
		arg.Mode,
		arg.CategoryID,
		arg.BusinessID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Amount,
		&i.Description,
		&i.PartyID,
		&i.Mode,
		&i.Direction,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
