// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEditRequest = `-- name: CreateEditRequest :one
INSERT INTO transaction_edit_requests (
    transaction_id,
    requested_by_id,
    type,
    requested_changes,
    reason,
    status
) VALUES (
    $1, 
    $2, 
    'edit', 
    $4::text::jsonb, -- <--- THE FIX
    $3, 
    'pending'
)
RETURNING id, transaction_id, requested_by_id, reviewed_by_id, status, type, requested_changes, reason, created_at, updated_at
`

type CreateEditRequestParams struct {
	TransactionID    pgtype.UUID `json:"transaction_id"`
	RequestedByID    pgtype.UUID `json:"requested_by_id"`
	Reason           pgtype.Text `json:"reason"`
	RequestedChanges string      `json:"requested_changes"`
}

func (q *Queries) CreateEditRequest(ctx context.Context, arg CreateEditRequestParams) (TransactionEditRequest, error) {
	row := q.db.QueryRow(ctx, createEditRequest,
		arg.TransactionID,
		arg.RequestedByID,
		arg.Reason,
		arg.RequestedChanges,
	)
	var i TransactionEditRequest
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.RequestedByID,
		&i.ReviewedByID,
		&i.Status,
		&i.Type,
		&i.RequestedChanges,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionWithValidation = `-- name: CreateTransactionWithValidation :one
WITH validation AS (
    SELECT 
        -- Check 1: Party must exist in this business
        EXISTS(
            SELECT 1 FROM parties 
            WHERE id = $3 AND business_id = $1
        ) AS party_valid,

        -- Check 2: Category must exist in this business (OR be NULL)
        (
            $4::uuid IS NULL OR 
            EXISTS(
                SELECT 1 FROM transaction_categories 
                WHERE id = $4 AND business_id = $1
            )
        ) AS category_valid
)
INSERT INTO transactions (
    business_id, 
    user_id, 
    party_id, 
    category_id, 
    amount, 
    direction, 
    mode, 
    receipt_no, 
    description
)
SELECT 
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6, 
    $7, 
    $8, 
    $9
FROM validation
WHERE party_valid = true AND category_valid = true
    RETURNING id, business_id, user_id, amount, direction, category_id, party_id, mode, receipt_no, description, created_at, updated_at
`

type CreateTransactionWithValidationParams struct {
	BusinessID  pgtype.UUID          `json:"business_id"`
	UserID      pgtype.UUID          `json:"user_id"`
	PartyID     pgtype.UUID          `json:"party_id"`
	CategoryID  pgtype.UUID          `json:"category_id"`
	Amount      pgtype.Numeric       `json:"amount"`
	Direction   TransactionDirection `json:"direction"`
	Mode        TransactionMode      `json:"mode"`
	ReceiptNo   string               `json:"receipt_no"`
	Description pgtype.Text          `json:"description"`
}

func (q *Queries) CreateTransactionWithValidation(ctx context.Context, arg CreateTransactionWithValidationParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransactionWithValidation,
		arg.BusinessID,
		arg.UserID,
		arg.PartyID,
		arg.CategoryID,
		arg.Amount,
		arg.Direction,
		arg.Mode,
		arg.ReceiptNo,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Amount,
		&i.Direction,
		&i.CategoryID,
		&i.PartyID,
		&i.Mode,
		&i.ReceiptNo,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionApprovals = `-- name: GetTransactionApprovals :many
SELECT 
    ter.id,
    ter.transaction_id,
    ter.type,
    ter.status,
    ter.requested_changes, -- Cast to text for Go
    ter.reason,
    ter.created_at,
    ter.updated_at,
    -- Requestor Details
    req_u.id AS requested_by_id,
    req_u.name AS requested_by_name,
    -- Reviewer Details
    rev_u.id AS reviewed_by_id,
    rev_u.name AS reviewed_by_name,
    -- NEW: Extracted Names from JSONB IDs
    p.name AS party_name,
    c.name AS category_name
FROM transaction_edit_requests ter
JOIN transactions t ON ter.transaction_id = t.id
JOIN users req_u ON ter.requested_by_id = req_u.id
LEFT JOIN users rev_u ON ter.reviewed_by_id = rev_u.id
LEFT JOIN parties p ON p.id = NULLIF(ter.requested_changes->>'party_id', '')::uuid
LEFT JOIN transaction_categories c ON c.id = NULLIF(ter.requested_changes->>'category_id', '')::uuid
WHERE 
    t.business_id = $1
    AND (
        $2::UUID[] IS NULL 
        OR ter.requested_by_id = ANY($2::UUID[])
    )
    AND (
        $3::text = '' OR ter.status::text = $3
    )
    AND (
        $4::text = '' OR ter.type::text = $4
    )
    AND (
        $5::TIMESTAMPTZ IS NULL 
        OR ter.created_at >= $5
    )
    AND (
        $6::TIMESTAMPTZ IS NULL 
        OR ter.created_at <= $6
    )
ORDER BY ter.created_at DESC
`

type GetTransactionApprovalsParams struct {
	BusinessID     pgtype.UUID        `json:"business_id"`
	RequestedByIds []pgtype.UUID      `json:"requested_by_ids"`
	Status         string             `json:"status"`
	Type           string             `json:"type"`
	FromDate       pgtype.Timestamptz `json:"from_date"`
	ToDate         pgtype.Timestamptz `json:"to_date"`
}

type GetTransactionApprovalsRow struct {
	ID               pgtype.UUID           `json:"id"`
	TransactionID    pgtype.UUID           `json:"transaction_id"`
	Type             TransactionChangeType `json:"type"`
	Status           EditRequestStatus     `json:"status"`
	RequestedChanges []byte                `json:"requested_changes"`
	Reason           pgtype.Text           `json:"reason"`
	CreatedAt        pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz    `json:"updated_at"`
	RequestedByID    pgtype.UUID           `json:"requested_by_id"`
	RequestedByName  pgtype.Text           `json:"requested_by_name"`
	ReviewedByID     pgtype.UUID           `json:"reviewed_by_id"`
	ReviewedByName   pgtype.Text           `json:"reviewed_by_name"`
	PartyName        pgtype.Text           `json:"party_name"`
	CategoryName     pgtype.Text           `json:"category_name"`
}

// GetTransactionApprovals returns approvals list based on filters
// Join Party: Extract ID from JSON -> Handle Empty String -> Cast to UUID -> Join
// Join Category: Extract ID from JSON -> Handle Empty String -> Cast to UUID -> Join
func (q *Queries) GetTransactionApprovals(ctx context.Context, arg GetTransactionApprovalsParams) ([]GetTransactionApprovalsRow, error) {
	rows, err := q.db.Query(ctx, getTransactionApprovals,
		arg.BusinessID,
		arg.RequestedByIds,
		arg.Status,
		arg.Type,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionApprovalsRow{}
	for rows.Next() {
		var i GetTransactionApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Type,
			&i.Status,
			&i.RequestedChanges,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestedByID,
			&i.RequestedByName,
			&i.ReviewedByID,
			&i.ReviewedByName,
			&i.PartyName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionForUpdate = `-- name: GetTransactionForUpdate :one

SELECT id, business_id, user_id, amount, direction, category_id, party_id, mode, receipt_no, description, created_at, updated_at FROM transactions 
WHERE id = $1 AND business_id = $2 
FOR NO KEY UPDATE
`

type GetTransactionForUpdateParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

// RETURNING id, created_at;
func (q *Queries) GetTransactionForUpdate(ctx context.Context, arg GetTransactionForUpdateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionForUpdate, arg.ID, arg.BusinessID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Amount,
		&i.Direction,
		&i.CategoryID,
		&i.PartyID,
		&i.Mode,
		&i.ReceiptNo,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    amount = $3,
    direction = $4,
    category_id = $5,
    party_id = $6,
    mode = $7,
    receipt_no = $8,
    description = $9,
    updated_at = NOW()
WHERE id = $1 AND business_id = $2
RETURNING id, business_id, user_id, amount, direction, category_id, party_id, mode, receipt_no, description, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          pgtype.UUID          `json:"id"`
	BusinessID  pgtype.UUID          `json:"business_id"`
	Amount      pgtype.Numeric       `json:"amount"`
	Direction   TransactionDirection `json:"direction"`
	CategoryID  pgtype.UUID          `json:"category_id"`
	PartyID     pgtype.UUID          `json:"party_id"`
	Mode        TransactionMode      `json:"mode"`
	ReceiptNo   string               `json:"receipt_no"`
	Description pgtype.Text          `json:"description"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.BusinessID,
		arg.Amount,
		arg.Direction,
		arg.CategoryID,
		arg.PartyID,
		arg.Mode,
		arg.ReceiptNo,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Amount,
		&i.Direction,
		&i.CategoryID,
		&i.PartyID,
		&i.Mode,
		&i.ReceiptNo,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyCategoryBelongsToBusiness = `-- name: VerifyCategoryBelongsToBusiness :one
SELECT EXISTS (
    SELECT 1 FROM transaction_categories 
    WHERE id = $1 AND business_id = $2
)
`

type VerifyCategoryBelongsToBusinessParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) VerifyCategoryBelongsToBusiness(ctx context.Context, arg VerifyCategoryBelongsToBusinessParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyCategoryBelongsToBusiness, arg.ID, arg.BusinessID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyPartyBelongsToBusiness = `-- name: VerifyPartyBelongsToBusiness :one
SELECT EXISTS (
    SELECT 1 FROM parties 
    WHERE id = $1 AND business_id = $2
)
`

type VerifyPartyBelongsToBusinessParams struct {
	ID         pgtype.UUID `json:"id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) VerifyPartyBelongsToBusiness(ctx context.Context, arg VerifyPartyBelongsToBusinessParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyPartyBelongsToBusiness, arg.ID, arg.BusinessID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
