// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    google_id,
    email,
    name,
    picture
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, google_id, email, name, phone_number, picture, created_at, updated_at
`

type CreateUserParams struct {
	GoogleID string      `json:"google_id"`
	Email    string      `json:"email"`
	Name     pgtype.Text `json:"name"`
	Picture  pgtype.Text `json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_id, email, name, phone_number, picture, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, google_id, email, name, phone_number, picture, created_at, updated_at FROM users
WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, google_id, email, name, phone_number, picture, created_at, updated_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleID,
			&i.Email,
			&i.Name,
			&i.PhoneNumber,
			&i.Picture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET 
    name = $2,
    phone_number = $3,
    updated_at = now()
WHERE 
    id = $1
RETURNING id, google_id, email, name, phone_number, picture, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one



WITH inserted AS (
  INSERT INTO users (google_id, email, name, picture)
  VALUES ($1, $2, $3, $4)
  ON CONFLICT (email) DO NOTHING
  RETURNING id, google_id, email, name, phone_number, picture, created_at, updated_at -- Key change 1: Return the *whole user row*, not just the id
)
SELECT id, google_id, email, name, phone_number, picture, created_at, updated_at FROM inserted -- Key change 2: Select the new user from the CTE
UNION
SELECT id, google_id, email, name, phone_number, picture, created_at, updated_at FROM users WHERE email = $2 -- Select the existing user if the CTE is empty
LIMIT 1
`

type UpsertUserByEmailParams struct {
	GoogleID string      `json:"google_id"`
	Email    string      `json:"email"`
	Name     pgtype.Text `json:"name"`
	Picture  pgtype.Text `json:"picture"`
}

type UpsertUserByEmailRow struct {
	ID          pgtype.UUID        `json:"id"`
	GoogleID    string             `json:"google_id"`
	Email       string             `json:"email"`
	Name        pgtype.Text        `json:"name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Picture     pgtype.Text        `json:"picture"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// -- name: UpsertUserByEmail :one
// WITH inserted AS (
//
//	INSERT INTO users (google_id, email, name)
//	VALUES ($1, $2, $3)
//	ON CONFLICT (email) DO NOTHING
//	RETURNING *
//
// )
// SELECT * FROM inserted
// UNION ALL
// SELECT * FROM users WHERE email = $2
// LIMIT 1;
// -- name: UpsertUserByEmail :one
// WITH inserted AS (
//
//	INSERT INTO users (google_id, email, name,picture)
//	VALUES ($1, $2, $3, $4)
//	ON CONFLICT (email) DO NOTHING
//	RETURNING id
//
// )
// SELECT u.*
// FROM users AS u
// WHERE u.id IN (
//
//	SELECT i.id FROM inserted AS i
//	UNION
//	SELECT u2.id FROM users AS u2 WHERE u2.email = $2
//
// )
// LIMIT 1;
func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (UpsertUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	var i UpsertUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PhoneNumber,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
