// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone_number, google_id, picture, is_trial_used, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.GoogleID,
		&i.Picture,
		&i.IsTrialUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, phone_number, google_id, picture, is_trial_used, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.GoogleID,
		&i.Picture,
		&i.IsTrialUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, name, email, phone_number, google_id, picture, is_trial_used, created_at, updated_at FROM users
WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.GoogleID,
		&i.Picture,
		&i.IsTrialUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, phone_number, google_id, picture, is_trial_used, created_at, updated_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.GoogleID,
			&i.Picture,
			&i.IsTrialUsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET 
    name = $2,
    phone_number = $3,
    updated_at = now()
WHERE 
    id = $1
RETURNING id, name, email, phone_number, google_id, picture, is_trial_used, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.GoogleID,
		&i.Picture,
		&i.IsTrialUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUsersTrialUsed = `-- name: UpdateUsersTrialUsed :exec
UPDATE users
SET 
    is_trial_used = $2,
    updated_at = now()
WHERE 
    id = $1
`

type UpdateUsersTrialUsedParams struct {
	ID          pgtype.UUID `json:"id"`
	IsTrialUsed bool        `json:"is_trial_used"`
}

// updates is_trial_used
func (q *Queries) UpdateUsersTrialUsed(ctx context.Context, arg UpdateUsersTrialUsedParams) error {
	_, err := q.db.Exec(ctx, updateUsersTrialUsed, arg.ID, arg.IsTrialUsed)
	return err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
WITH inserted AS (
  INSERT INTO users (google_id, email, name, picture)
  VALUES ($1, $2, $3, $4)
  ON CONFLICT (email) DO NOTHING
  RETURNING id, name, email, phone_number, google_id, picture, is_trial_used, created_at, updated_at -- Key change 1: Return the *whole user row*, not just the id
)
SELECT id, name, email, phone_number, google_id, picture, is_trial_used, created_at, updated_at FROM inserted -- Key change 2: Select the new user from the CTE
UNION
SELECT id, name, email, phone_number, google_id, picture, is_trial_used, created_at, updated_at FROM users WHERE email = $2 -- Select the existing user if the CTE is empty
LIMIT 1
`

type UpsertUserByEmailParams struct {
	GoogleID string      `json:"google_id"`
	Email    string      `json:"email"`
	Name     pgtype.Text `json:"name"`
	Picture  pgtype.Text `json:"picture"`
}

type UpsertUserByEmailRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        pgtype.Text        `json:"name"`
	Email       string             `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	GoogleID    string             `json:"google_id"`
	Picture     pgtype.Text        `json:"picture"`
	IsTrialUsed bool               `json:"is_trial_used"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (UpsertUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	var i UpsertUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.GoogleID,
		&i.Picture,
		&i.IsTrialUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
